name: Run unit tests

on:
  push:
    branches:
      - master
    paths:
      - *.go
  pull_request:
    branches:
      - "*"
    paths:
      - *.go

jobs:
  test:
    name: "Run unit test"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Prepare dependencies
        run: |
          go mod download

      - name: Run unit tests
        run: |
          go test -race .
